name: Deploy MQTT Broker Image to ECR
run-name: ${{github.actor}} deployed mqtt to ecr
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"
        type: string
        required: true

jobs:
  build-push-image:
    name: Push Image to ECR
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::722663008165:role/GitHubOpenIDECRRole
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: check working dir
        run: |
          ls -alh

      - name: Build, tag, and push image to Amazon ECR
        working-directory: ./
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: gateway_runtime # the ECR repo name
          IMAGE_TAG: v1 # The image tag, it could be the commit SHA: ${{ github.sha }}
        run: |
          docker compose build
          docker push mqtt-broker